"""
Shared venue alias table — single source of truth for both mica_update.py and
booking_plan_update.py.  Maps booking-sheet theatre names (lowercase) to the
exact Mica venue name used in the plans / holdovers tables.

To add new aliases: edit CITY_VENUE_ALIASES below.  Changes apply to BOTH the
Holdover Assistant and Booking Assistant tabs automatically.
"""
# fmt: off

CITY_VENUE_ALIASES: dict[str, str] = {
    "espanola, nm":      "dreamcatcher 10",
    "espanola nm":       "dreamcatcher 10",
    "espanola":          "dreamcatcher 10",
    "independence, mo":  "pharaoh independence 4",
    "independence mo":   "pharaoh independence 4",
    "guymon, ok":        "northridge guymon 8",
    "guymon ok":         "northridge guymon 8",
    "florence, sc":      "julia florence 4",
    "florence sc":       "julia florence 4",
    "tulsa, ok":         "eton tulsa 6",
    "tulsa ok":          "eton tulsa 6",
    "kirksville, mo":    "downtown kirksville 8",
    "kirksville mo":     "downtown kirksville 8",
    "marion, nc":        "hometown cinemas marion 2",
    "marion nc":         "hometown cinemas marion 2",
    "fulton, mo":        "fulton cinema 8",
    "fulton mo":         "fulton cinema 8",
    "lumberton, nc":     "hometown lumberton 4",
    "lumberton nc":      "hometown lumberton 4",
    "marshall, mo":      "cinema marshall 3",
    "marshall mo":       "cinema marshall 3",
    "milford, ia":       "pioneer milford 1",
    "milford ia":        "pioneer milford 1",
    "parsons, ks":       "the parsons theatre",
    "parsons ks":        "the parsons theatre",
    "lamar, mo":         "plaza lamar 1",
    "lamar mo":          "plaza lamar 1",
    "borger, tx":        "morley borger 5",
    "borger tx":         "morley borger 5",
    "mountain grove, mo": "fun city 5 cinemas",
    "mountain grove mo":  "fun city 5 cinemas",
    "mountain grove":     "fun city 5 cinemas",
    # ── Mary Ann B. Silk (Golden Ticket / mixed independent circuit) ─────────
    # All venues fail naturally: "golden" + "ticket" inflate denom to 3+, so
    # single-word bare city/brand names can't reach ratio ≥ 0.8.
    "aberdeen":          "Golden Ticket Cinemas Aberdeen 5",
    "ale house":         "Golden Ticket Cinemas Greensboro Ale House 10",
    "ale house plf":     "Golden Ticket Cinemas Greensboro Ale House 10",
    "bloomington":       "Golden Ticket Bloomington Ale House 10",
    "bluefield":         "Golden Ticket Cinemas Bluefield 8",
    "clarion":           "Golden Ticket Clarion 5",
    "cloquet":           "Premiere Cloquet 6",
    "dickinson":         "Golden Ticket Dickinson 3",
    "dublin":            "Golden Ticket Cinemas Dublin 6",
    "dubois":            "Golden Ticket Cinemas DuBois 5",
    "greenville":        "Golden Ticket Cinemas Greenville Grande 14",
    "greenville plf":    "Golden Ticket Cinemas Greenville Grande 14",
    "harrison":          "Golden Ticket Cinemas Harrison 8",
    "hastings":          "Golden Ticket Cinemas Hastings 3",
    "jamestown":         "Bison 6 Cinema",
    "kearney":           "Golden Ticket Cinemas Hilltop 4",
    "lenoir":            "Golden Ticket Cinemas Twin 2",
    "madisonville":      "Golden Ticket Cinemas Capitol 8",
    "meridian":          "Golden Ticket Cinemas Meridian 6",
    "middlesboro":       "Golden Ticket Cinemas Middlesboro 4",
    "north platte":      "Golden Ticket Cinemas Platte River 6",
    "onamia":            "Grand Makwa Cinema Onamia 4",
    "rapid city":        "Golden Ticket Cinemas Rushmore 7",
    "rhinelander":       "Rouman Cinema Rhinelander 6",
    "scottsbluff":       "Golden Ticket Cinemas Reel Lux 6 *temp 4*",
    "shawnee":           "Golden Ticket Cinemas Shawnee 6",
    "shawnee plf":       "Golden Ticket Cinemas Shawnee 6",
    "sioux falls":       "West Mall 7 Theatres",
    "st. clairsville":   "Golden Tickets St. Clairsville 5",
    "waynesville":       "Smoky Mountain Cinema 3",
    "willmar":           "Golden Ticket Cinemas Kandi 6",
    "worthington":       "New Grand Theatre",
    "minot":             "Oak Park Theater 1",
    "spooner":           "Palace Spooner 2",
    "valley city":       "Valley Twin Cinema 2",
    "luverne":           "Verne Drive-in Luverne 1",
    # AMC booking-name → Mica venue name (name differs from what parser extracts)
    "mt vernon 8":              "Mount Vernon 8",
    "mesa grand 14":            "Mesa Grande 14",
    "southern hill 12":         "Southern Hills 12",
    "arrowhead town center 14": "Arrowhead 14",
    "tulsa 12":                 "Tulsa Hills 12",
    "southroads 20":            "Southroads Tulsa 20",
    "foothills 15":             "Foothills Tucson 15",
    "surprise 14":              "Surprise Pointe 14",
    # Regal/Becky Williams — "Stm" suffix stripped by STOP, but these need city disambiguation
    "champlain centre stm 8":        "Champlain Plattsburgh 8",
    "e. greenbush 8":                "East Greenbush 8",
    "aviation mall 9":               "Aviation Mall Queensbury 9",
    "manor stm 16":                  "Regal Manor Cinema Lancaster 16",
    "new river valley stm 14 & rpx": "Regal New River Valley Christiansburg 14",
    "west manchester stm 13":        "Regal West Manchester York 13",
    "destiny usa stm 19 imax & rpx": "Regal Destiny Mall Cinema Syracuse 17",
    # Michael Davis (Regal NC/SC circuit)
    "stonecrest stm 22 imax & rpx":  "Regal Stonecrest @ Piper Glen Charlotte 22",
    "sandhill stm 16 imax & rpx":    "Regal Sandhill Columbia 14",
    "birkdale stm 16 & rpx":         "Regal Birkdale Huntersville 16",
    "franklin square stm 14":        "Regal Franklin Square Gastonia 14",
    "palmetto grande stm 16":        "Regal Palmetto Grande Mt Pleasant 16",
    "spartan stm 16":                "Regal Spartan Spartanburg 16",
    # Ashley Harris (Regal OH/IN/KY/WV/MI circuit)
    "coldwater crossing stm 14":     "Regal Coldwater Fort Wayne 14",
    "deerfield twn ctr stm 16 & rpx": "Regal Deerfield Towne Center Mason 16",
    "greenwood stm 14 & rpx":        "Regal Greenwood 14",
    "willoughby commons stm 16":     "Regal Willoughby Commons 16",
    "lansing mall stm 12 & rpx":     "Regal Lansing Mall 12",
    "galaxy stm 14":                 "Regal Galaxy Indianapolis 14",
    "nitro stm 12":                  "Regal Nitro 12",
    "wilder stm 14":                 "Regal Wilder 14",
    "village park cinema stm 17":    "Regal Village Park Carmel 17",
    # Daniel Worsham (Regal GA/TN/KY/SC circuit)
    "clarksville stm 16 & rpx":      "Regal Clarksville 16",
    # Alanna Peffley (Regal FL/VA/NC circuit)
    "regal dania point 4dx rpx &vip":    "Regal Dania Pointe 16",
    "regal dania point 4dx rpx & vip":   "Regal Dania Pointe 16",
    "regal bistro at the falls":          "Regal Falls Miami 12",
    "kendall vlg stm 16 imax & rpx":     "Regal Kendall Village Miami 16",
    "pavilion stm 14 & rpx":             "Regal Pavilion Port Orange 14",
    "belltower stm 20":                  "Regal Belltower Ft Myers 20",
    "winter park village 20 & rpx":      "Regal Winter Park Village 16",
    "royal palm beach stm 18 & rpx":     "Regal Royal Palm Plaza Royal Palm Beach 12",
    # Regal/Rich Motzer — abbreviated venue names
    "natomas mktplace stm 16 & rpx": "Natomas Marketplace 16",
    "stockton cty ctr stm 16 & imax":"Stockton City Center 16",
    "el dorado stm 14 & imax":       "Regal El Dorado Hills 14",
    "hacienda stm 20 imax & rpx":    "Regal Hacienda Crossings Dublin 20 & IMAX",
    # Regal/Christopher Lauderdale — stm-only sig-word venues need city disambiguation
    "auburn stm 17":                "Auburn Stadium 17",
    "bridgeport stm 18 & imax":     "Bridgeport Tigard 18",
    "cascade stm 16 imax & rpx":    "Cascade Vancouver 16",
    "cinema 99 stm 11":             "Cinema 99 Vancouver",
    "city center stm 12":           "City Vancouver 12",
    "movies on tv stm 16":          "Movies Hillsboro 16",
    "santiam stm 11":               "Santiam Salem 11",
    "stark street stm 10":          "Stark Gresham 10",
    # Clarence Chiu (Regal Pacific NW / LA / NV circuit)
    "aliante stm 16 & imax":           "Regal Aliante N Las Vegas 16",
    "barkley vlg stm 16 imax & rpx":  "Regal Barkley Village Bellingham 16 IMAX & RPX",
    "bella bottega stm 11":            "Regal Bella Bottega Redmond 11",
    "boulder station stm 11":          "Regal Boulder Station Las Vegas 11",
    "carlsbad 12":                     "Regal Carlsbad 12",
    "escondido stm 16 & imax":        "Regal Escondido Stadium 16",
    "everett stm 16 & rpx":           "Regal Everett Stadium 16 & RPX",
    "issaquah stm 12 imax & rpx":     "Regal Issaquah Highland IMAX & RPX 12",
    "martin village stm 16 & imax":   "Regal Martin Village Lacey 16",
    "marysville 14":                   "Regal Marysville 14",
    "meridian 16":                     "Regal Meridian 16",
    "mira mesa stm 18 & imax & rpx": "Regal Mira Mesa San Diego 18",
    "oceanside stm 16":               "Regal Oceanside Stadium 16",
    "parkway plaza stm 18 & imax":    "Regal Parkway Plaza El Cajon 18",
    "poulsbo stm 10":                  "Regal Poulsbo 10",
    "rancho del rey stm 16":          "Regal Rancho Del Rey Chula Vista 16",
    "rancho san diego stm 15":        "Regal Rancho San Diego 15",
    "red rock stm 16 & imax":        "Regal Red Rock Las Vegas 16",
    "regal mission marketplace rpx":  "Regal Mission Marketplace 20",
    "san marcos stm 18":              "Regal San Marcos 18",
    "sunset station stm 13 & imax":  "Regal Sunset Station Henderson 13",
    "the landing stm 14 & rpx":      "Regal The Landing Renton 14 & RPX",
    "thornton place stm 14 & imax":  "Regal Thornton Place Seattle 14 & IMAX",
    # Celebration! Cinema (Zach Righetti) — booking names differ from Mica abbreviated names
    "cinema carousel 16":               "Celebration Cinema Carousel",
    "crossroads 15 + imax":             "Celebration Crossroads Imax",
    "rivertown 13 + c premium":         "Celebration Cinema Rivertown",
    "grand rapids north 17 + imax":     "Celebration Cinema GR North",
    "grand rapids south 15 + c premium":"Celebration South",
    "lansing 19 + c premium xl":        "Celebration Lansing Imax",
    "mt. pleasant 11":                  "Celebration Mt Pleasant",
    "benton harbor 14 + dbox":          "Celebration! Benton Harbor",
    # Hooky Entertainment / Tammy Flores — Hutto has no city in venue name; RedStone spelling
    "hooky entertainment + sdx + imax, hutto": "Hooky Entertainment + SDX + IMAX Hutto 8",
    "hooky entertainment + sdx + imax":        "Hooky Entertainment + SDX + IMAX Hutto 8",
    "redstone 14 cinemas w/pdx":               "Red Stone 14 Cinemas",
    "redstone 14 cinemas":                     "Red Stone 14 Cinemas",
    # Kaitlin Privitera (AMC KC/Midwest) — report short names differ from Mica names
    "studio 28":               "AMC Studio Olathe 30",
    "independence 20":         "AMC Independence Commons 20",
    "prairiefire 17":          "AMC DINE-IN Prairie Fire 17",
    "legends 14":              "AMC Legends Kansas City 14",
    "northrock 14":            "AMC Northrock Wichita 14",
    "springfield 11":          "AMC Springfield 11",
    # James Douglas (AMC SE/Florida) — report short names differ from Mica names
    "regency 24":            "AMC Regency Sq Jacksonville 24 & IMAX",
    "aventura mall 24":      "AMC Aventura 24 & IMAX",
    "sunset place 24":       "AMC Sunset S Miami 24 & IMAX",
    "weston 8":              "AMC Weston Cinema Sunrise 8",
    "bayou 15":              "AMC Bayou Pensacola 15 & IMAX",
    "avenue 16":             "AMC Avenue Melbourne 16",
    "tallahassee 20":        "AMC Tallahassee Mall 20 & IMAX",
    "veterans expressway 24":"AMC Veterans Tampa 24 & IMAX",
    "regency 20":            "AMC Regency Sq Brandon 20 & IMAX",
    "woodlands square 20":   "AMC Woodland Sq Oldsmar 20 & IMAX",
    "riverview 14":          "AMC Riverview Gibsonton 14",
    "westshore plaza 14":    "AMC Westshore Tampa 14",
    "sundial 12":            "AMC Sundial St Petersburg",
    "coral ridge 10":        "AMC Coral Ridge Ft Lauderdale 10",
    "pensacola 18":          "AMC CLASSIC Pensacola 18",
    # Sergio Candelas (AMC Central/Southwest) — report short names differ from Mica names
    "quail springs mall 24":       "AMC Quail Springs Oklahoma City 24 & IMAX",
    "town square 18":              "AMC Town Square Las Vegas 18 & IMAX",
    "decatur 10":                  "AMC CLASSIC Decatur 10",
    "springfield 12":              "AMC CLASSIC Springfield 12 with IMAX",
    "springfield 8":               "AMC Springfield 8",
    "esplanade 14":                "AMC DINE-IN Esplanade 14",
    "mt vernon 8":                 "AMC CLASSIC Mount Vernon 8",
    "arrowhead town center 14":    "AMC Arrowhead 14",
    "mesa grand 14":               "AMC Mesa Grande 14",
    "southern hill 12":            "AMC Southern Hills 12",
    "tulsa 12":                    "AMC CLASSIC Tulsa Hills 12",
    "surprise 14":                 "AMC Surprise Pointe 14",
    "foothills 15":                "AMC Foothills Tucson 15",
    "southroads 20":               "AMC Southroads Tulsa 20",
    # Ron Wooley (AMC NE) — report short names differ from Mica names
    "plainville 20":   "AMC Plainville Cinema 20",
    "palisades 21":    "AMC Palisades Center 21",
    "freehold 14":     "AMC Freehold Metroplex 14",
    "aviation 12":     "AMC Aviation Linden 12",
    "levittown 10":    "AMC DINE-IN Levittown 10",
    "landmark 8":      "AMC Landmark 8",
    "newport centre 11": "AMC Newport Centre Jersey City 11",
    # Dave Glass (AMC) — report short names differ from Mica names
    "southlands 16":        "AMC Southlands Aurora 16",
    "flatiron crossing 14": "AMC Flatiron Broomfield 14",
    "orchard 12":           "AMC Orchard Town Center Westminster 12",
    "mayfair 18":           "AMC Mayfair Mall Wauwatosa 18",
    "southdale center 16":  "AMC Southdale Edina 16",
    "southgate 9":          "AMC DINE-IN Southgate 9",
    "southcenter 16":       "AMC Southcenter Tukwila 16 & IMAX",
    "factoria 8":           "AMC Factoria Bellevue 8",
    "alderwood 16":         "AMC Alderwood Lynnwood 16",
    # Kathryn Wintermyer (AMC Detroit/OH/PA) — report short names differ from Mica names
    "forum 30":             "AMC Forum Sterling Heights 17",
    "gratiot 15":           "AMC Star Gratiot Clinton Township 15",
    "john r 15":            "AMC John R Theatre 15",
    "stonybrook 20":        "AMC Stonybrook Louisville 20",
    "309 cinema 9":         "AMC 309 Cinemas North Wales 9",
    "berkshire 8":          "AMC Berkshire Wyomissing 8",
    "marlton 8":            "AMC Marlton Cinemas 8",
    "westmoreland 15":      "AMC Westmoreland Greensburg 15",
    "fairground 10":        "AMC Fairgrounds 10",
    "marketfair 10":        "AMC Marketfair Princeton 10",
    # ── Tom McCauley (AMC New England / Mid-Atlantic) ─────────────────────────
    "methuen 20":           "AMC Methuen at the Loop 20",
    "hampton 24":           "AMC Hampton Towne Centre 24",
    "loudoun 11":           "AMC Loudoun Station Ashburn 11",
    "worldgate 9":          "AMC Worldgate Herndon 9",
    "columbia mall 14":     "AMC Columbia Maryland 14",
    "mj capital center 12": "AMC Magic Johnson Capital Center 12",
    "st charles towne center 9": "AMC St. Charles Waldorf 9",
    "academy 8":            "AMC Academy Greenbelt 8",
    # ── Justin Johnson (AMC Chicago / Midwest / Indiana / Rockford) ───────────
    "yorktown 18":          "AMC Yorktown Lombard 18",
    "galewood 14":          "AMC Galewood Crossings 14",
    "hawthorn 12":          "AMC Hawthorn Vernon Hills 12",
    "randhurst 12":         "AMC Randhurst Mount Prospect 12",
    "peru 8":               "AMC Peru Mall 8",
    "castleton square 14":  "AMC Castleton Indianapolis 14",
    "washington sq 12":     "AMC Washington Square 12",
    # ── Dan Cammarata (AMC Texas / SE — DFW / Houston / SA / Austin / Savannah) ─
    "northpark 15":              "AMC North Park Dallas 15 & IMAX",
    "lakeline 9":                "AMC Lakeline Mall Cedar Park 9",
    "fountains 18":              "AMC Fountains Stafford 18 & IMAX",
    "rivercenter 11":            "AMC Rivercenter San Antonio 9",
    "sikes 10":                  "AMC Sikes Senter 10",
    "corpus 16":                 "AMC Corpus Christi 16",
    "stonebriar mall 24":        "AMC Stonebriar Frisco 24 & IMAX",
    "firewheel town center 18":  "AMC Firewheel Garland 18",
    "eastchase 9":               "AMC Eastchase Ft Worth 9",
    "willowbrook 24":            "AMC Willowbrook Houston 24",
    "brazos 14":                 "AMC Brazos Stadium Lake Jackson 14",
    # ── Devan Tolbert (AMC SE / Louisiana / Carolinas) ───────────────────────
    "hanes 12":                  "AMC Hanes Winston Salem 12",
    "houma palace 10":           "AMC Houma 10 *TEMP 9*",
    # ── Brandon Ferguson (AMC LA / San Diego / Sacramento / SF Bay Area) ────────
    "orange 30":                 "AMC Block Orange 30 & IMAX",
    "tyler 16":                  "AMC Tyler Riverside 16 & IMAX",
    "mercado 20":                "AMC Mercado Santa Clara 20 & IMAX",
    "metreon 16":                "AMC Metreon San Francisco 16 & IMAX",
    "eastridge 15":              "AMC Eastridge Mall San Jose 15 & IMAX",
    "saratoga 14":               "AMC Saratoga San Jose 14 & IMAX",
    # ── Kelsey Kash (AMC AL / TN / Chattanooga / Knoxville / Tri-Cities) ────────
    "dothan pavilion 12":        "AMC CLASSIC Dothan Pavillion 12",
    "vestavia 10":               "AMC DINE-IN Vestavia Hills 10",
    "battlefield 10":            "AMC CLASSIC Battlefield Ft Oglethorpe 10",
    "thoroughbred 20":           "AMC Thoroughbred Franklin 20 & IMAX",
    "stones river 9":            "AMC Stone River 9",
    "southlake pavilion 24":     "AMC Southlake Morrow 23 & IMAX",
    "colonial 18":               "AMC Colonial Lawrenceville 18",
    "parkway pointe 15":         "AMC Parkway Point Atlanta 15",
    # ── David Saunders (Pacific NW / OR / WA indie circuit) ──────────────────
    "bremerton":                 "SEEfilm Cinema",
    "cinestars":                 "Hood River Cinemas 5",
    "coast":                     "Coast Fort Bragg 4",
    "milwaukie":                 "Milwaukie Portland 2",
    "living room pdx":           "Living Room Theatres Portland",
    "living room indy":          "Living Room Theaters Indianapolis",
    "battle ground":             "Battle Ground Cinema 8",
    "canby":                     "Canby Cinema 8",
    "independence":              "Independence Cinema 8",
    "oak grove":                 "Oak Grove Portland 8",
    "roseburg":                  "Roseburg Cinema",
    "sandy":                     "Sandy Cinema 8",
    "scappoose":                 "Scappoose Cinema 7",
    # ── Blue Smiley / CFB Epic + GTC (Rentrak-grid fallback for fuzzy failures) ─
    "regency square 8":              "Epic Regency Cinema Stuart 8",
    # ── Glen Parham GTC — defensive fallbacks (city+state lookup handles these;
    #    aliases fire only if raw booking name reaches JS fuzzy matcher) ─────────
    "riverwatch":                    "GTC Riverwatch Cinemas 12",
    "gateway 7":                     "GTC Gateway 7",
    "island 7":                      "GTC Island 7",
    "smithfield cinemas 10":         "GTC Smithfield 10",
    "valdosta stadium 15 w/gtx":     "GTC Valdosta 15",
    "pooler stadium 14 w/gtx":       "GTC Pooler 14",
    "mall 7":                        "GTC Mall Cinemas 7",
    "evans 14":                      "GTC Evans 14",
    "liberty 9":                     "GTC Liberty 9",
    "mountain cinemas 8":            "GTC Mountain Cinemas 8",
    "university 16 cinemas w/gtx":   "GTC University 16",
    "moultrie stadium 6 cinemas":    "GTC Moultrie 6",
    "danville stadium 12":           "GTC Danville 12",
    # ── Cinemark DFW (Eric Bond) — historical/local names → Mica master names ──
    "cinemark central plano 10":          "cinemark movies plano 10",
    "cut! by cinemark":                   "cinemark cut! 10",
    "cinemark 17":                        "cinemark 17 + imax",
    "rave ridgmar 13":                    "cinemark ridgmar mall 13 + xd",
    "rave north east mall 18":            "cinemark northeast mall 18 + xd",
    "cinemark cleburne":                  "cinemark cinema cleburne 6",
    "cinemark 12 and xd":                 "cinemark mansfield 12 + xd",
    "tinseltown grapevine and xd":        "cinemark tinseltown grapevine 17 + xd",
    "cinemark 17 + imax":                 "cinemark tulsa 17",
    "cinemark 14, cedar hill":            "cinemark cedar hill 14",
    "movies 14, lancaster":               "cinemark movies lancaster 14",
    "cinemark 14, denton":                "cinemark denton 14",
    "cinemark 12, sherman":               "cinemark sherman 12",
    "movies 8, paris":                    "cinemark movies paris 8",
    "cinemark west plano, plano":         "cinemark movies plano 10",
    "cinemark west plano":                "cinemark movies plano 10",
    "cinemark (the legacy), plano":       "cinemark legacy 24 + xd",
    "cinemark (the legacy)":              "cinemark legacy 24 + xd",
    "cinemark allen 16 and xd, allen":    "cinemark allen 16 + xd",
    "cinemark allen 16 and xd":           "cinemark allen 16 + xd",
    "cinemark roanoke 14, roanoke":       "cinemark roanoke 14 + xd",
    "cinemark roanoke 14":                "cinemark roanoke 14 + xd",
    "cinemark rockwall 14 and xd, rockwall": "cinemark rockwall 14 + xd",
    "cinemark rockwall 14 and xd":        "cinemark rockwall 14 + xd",
    # ── Cinemark national shorthand → Mica full name ─────────────────────────
    "tinseltown usa, jacksonville":       "cinemark tinseltown jacksonville 20 + xd",
    "tinseltown usa, fayetteville":       "cinemark tinseltown fayetteville 17 + xd",
    "tinseltown usa, north aurora":       "cinemark tinseltown north aurora 17 usa",
    "cinemark orlando and xd":            "cinemark festival bay orlando 20 + xd",
    "cinemark orlando and xd, orlando":   "cinemark festival bay orlando 20 + xd",
    "cinemark west dundee, il":           "cinemark spring hill mall 8 + xd",
    "cinemark west dundee":               "cinemark spring hill mall 8 + xd",
    "movies 8 ladson oakbrook ii":        "cinemark movies summerville 8",
    "movies 8 ladson oakbrook ii, summerville": "cinemark movies summerville 8",
    "movies 10, bourbonnais":             "cinemark movies bourbonnais 10",
    "movies 10":                          "cinemark movies bourbonnais 10",
    "cinemark louis joliet mall":         "cinemark louis joliet mall 14",
    "deer park 16":                       "cinemark century deer park 16",
    "deer park 16, deer park":            "cinemark century deer park 16",
    "valparaiso commons shopping center": "cinemark at valparaiso 12",
    "cinemark palace 20, boca raton":     "cinemark palace 20 + xd",
    "cinemark palace 20":                 "cinemark palace 20 + xd",
    "cinemark paradise 24, davie":        "cinemark paradise 24 + xd",
    "cinemark paradise 24":               "cinemark paradise 24 + xd",
    "cinemark bluffton, bluffton":        "cinemark bluffton 12",
    "cinemark bluffton":                  "cinemark bluffton 12",
    "cinemark seven bridges":             "cinemark 7 bridges woodridge 16 imax",
    "cinemark seven bridges, woodridge":  "cinemark 7 bridges woodridge 16 imax",
    # ── Cinemark general overrides ────────────────────────────────────────────
    "cinemark 22 + imax":                 "cinemark lancaster 22",
    "cinemark 22 + imax, lancaster":      "cinemark lancaster 22",
    "cinemark 16 +xd, victorville":       "cinemark victorville 16 + xd",
    # ── Cinemark Taylor Reynolds (SW/UT/AZ/NV) ────────────────────────────────
    "cinemark 16, mesa":                  "cinemark mesa 16",
    "cinemark 16, provo":                 "cinemark provo 16",
    "cinemark 24 + xd, west jordan":      "cinemark west jordan 24+xd",
    "imperial valley 14, el centro":      "cinemark century imperial valley mall 14",
    "imperial valley 14":                 "cinemark century imperial valley mall 14",
    "sierra vista 10, sierra vista":      "cinemark sierra vista 10",
    "sierra vista 10":                    "cinemark sierra vista 10",
    "cinemark spanish fork + xd, spanish fork": "cinemark spanish fork 8+xd",
    "cinemark spanish fork + xd":         "cinemark spanish fork 8+xd",
    "henderson 12, henderson":            "cinemark cinedome 12 (henderson)",
    "henderson 12":                       "cinemark cinedome 12 (henderson)",
    "cinemark draper + xd, draper":       "cinemark draper 12 + xd",
    "cinemark draper + xd":               "cinemark draper 12 + xd",
    "cinemark farmington + xd, farmington": "cinemark farmington 14+ xd",
    "cinemark farmington + xd":           "cinemark farmington 14+ xd",
    "cinemark riverton + xd, riverton":   "cinemark riverton ridgewood 14 +xd",
    "cinemark riverton + xd":             "cinemark riverton ridgewood 14 +xd",
    "century el con + xd, tucson":        "cinemark century 20 el con and xd (tucson)",
    "century el con + xd":                "cinemark century 20 el con and xd (tucson)",
    "cinemark 12, american fork":         "cinemark american fork 12",
    # ── Cinemark Pacific NW (Josh Wymer) ─────────────────────────────────────
    "lincoln square cinema with imax":    "cinemark lincoln square cinemas imax 16",
    "lincoln square cinema bistro 6":     "cinemark reserve lincoln square dine-in 6",
    "cinemark totem lake + xd":           "cinemark village at totem lake 8",
    "century walla walla grand cinema 12":"cinemark walla walla grand cinema12",
    "century arden and xd, sacramento":   "cinemark century arden + xd 14",
    "century arden and xd":               "cinemark century arden + xd 14",
    "century marina + xd, marina":        "cinemark century marina + xd 5",
    "century marina + xd":                "cinemark century marina + xd 5",
    "cinemark 17, springfield":           "cinemark springfield 17",
    # ── Diane Johnson (CSC) — Waikoloa name has no Mica city word ─────────────
    "waikoloa 3":                         "waikoloa village cinema 3",
    # ── Watson / Imagine Cinemas Canada ──────────────────────────────────────
    # Bare city/location names used by Richard Watson (Imagine + Cinestarz groups)
    "promenade mall":                     "imagine cinemas promenade 6",
    "london":                             "imagine cinemas london",
    "lakeshore windsor":                  "imagine cinemas lakeshore",
    "alliston":                           "imagine cinemas alliston",
    # ── Watson / Cinestarz (CineStarz Quebec/Ontario) ─────────────────────────
    "cote des nieges":                    "cine starz cote-des-neiges 7",
    "cote-des-nieges":                    "cine starz cote-des-neiges 7",
    "deluxe taschereau":                  "cine starz taschereau 12",
    "deluxe longueuil":                   "cinestarz longueuil 14",
    "burlington":                         "cine starz burlington",
    "st. laurent":                        "cine starz st laurent centre",
    "st laurent":                         "cine starz st laurent centre",
    # ── Tearlach Hutcheson (Cinepolis / Moviehouse & Eatery) ─────────────────
    # Mica splits "Mc Kinney" → sigWords produces ["kinney"] only; booking "mckinney" ≠ "kinney"
    "moviehouse & eatery mckinney 10":    "Moviehouse & Eatery Mc Kinney 10 (TX)",
    # ── Celeste Raymond (Landmark Cinemas Canada) ────────────────────────────
    # Only Surrey needs an alias — booking uses city name but Mica uses sub-brand "Guildford"
    "landmark 12 surrey":                 "Landmark Guildford 12",
    # ── Zach Righetti (Loeks / Celebration! Cinemas Michigan) ────────────────
    # "Celebration!" brand word not in CIRCUIT_WORDS → stays in denom; "GR" = 2 chars filtered;
    # "C Premium"/"IMAX" stripped as CIRCUIT_WORDS; all 7 below fail naturally → alias required
    "grand rapids north 17 + imax":       "Celebration! Cinema GR North",
    "rivertown 13 + c premium":           "Celebration! Cinema Rivertown",
    "grand rapids south 15 + c premium":  "Celebration! South",
    "lansing 19 + c premium xl":          "Celebration! Lansing & Imax",
    "cinema carousel 16":                 "Celebration! Cinema Carousel",
    "crossroads 15 + imax":               "Celebration! Crossroads & Imax",
    "mt. pleasant 11":                    "Celebration! Mt. Pleasant",
    # ── Matt Culbertson / IBS (Indiana Booking Service) ──────────────────────
    # Bare city names used by IBS; venue names in Mica differ substantially
    "goshen":                             "linway plaza goshen 14",
    "jerseyville":                        "the stadium theater 3",
    "litchfield":                         "westside litchfield 3",
    "rensselaer":                         "fountain stone theaters rensselaer 5",
    "nappanee theatre":                   "nappanee theatre 1",
    "goshen, in":                         "linway plaza goshen 14",
    "jerseyville, il":                    "the stadium theater 3",
    "litchfield, il":                     "westside litchfield 3",
    "rensselaer, in":                     "fountain stone theaters rensselaer 5",
    # ── Jennifer Solorzano (Cinemark CO / NM / TX West circuit) ─────────────
    "cinemark 12, greeley":               "cinemark greeley 12",
    "cinemark 16, fort collins":          "cinemark fort collins 16",
    "main place 6, mcallen":              "cinemark movies 6",
    "main place 6":                       "cinemark movies 6",
    "cinemark 16 + xd, brownsville":      "cinemark brownsville 16 + xd",
    "cinemark 16 + xd, harlingen":        "cinemark harlingen 16 + xd",
    "cinemark abilene and xd, abilene":   "cinemark abilene 12",
    "cinemark abilene and xd":            "cinemark abilene 12",
    # ── Andy Anderson (Cinemark SF Bay Area) ─────────────────────────────────
    "century at hayward, hayward":        "cinemark century at hayward 12",
    "century at hayward":                 "cinemark century at hayward 12",
    # ── Beth Teal (Cinemark East / Midwest) ──────────────────────────────────
    "cinemark towson + xd, towson":           "cinemark towson 15 + xd",
    "cinemark towson + xd":                   "cinemark towson 15 + xd",
    "cinemark 15 + xd, hadley":               "cinemark hadley 15 + xd",
    "cinemark tinseltown + xd, louisville":   "cinemark tinseltown louisville + xd",
    "cinemark paducah, paducah":              "cinemark paducah 12",
    "cinemark paducah":                       "cinemark paducah 12",
    # ── Jennifer Hernandez (Cinemark SoCal — LA / Palm Springs) ─────────────
    "cinemark 12 and xd, los angeles":        "cinemark 12 howard hughes la and xd",
    "cinemark 16, palmdale":                  "cinemark antelope valley mall palmdale 16",
    "century la quinta + xd, la quinta":      "cinemark century la quinta 12 + xd",
    # ── Allie Fullmer (Cinemark TX — Houston / Austin / SA / Corpus) ─────────
    "tinseltown 17 + xd, the woodlands":     "cinemark the woodlands 17 + xd",
    "tinseltown 17 + xd, jacinto city":      "cinemark tinseltown jacinto city 17 + xd",
    "tinseltown 290 16 + xd, houston":       "cinemark tinseltown 290 houston 16 + xd",
    "tinseltown 20 + xd, pflugerville":      "cinemark tinseltown pflugerville 20 + xd",
    "cinemark 18 + xd, webster":             "cinemark webster 18 + xd",
    "hollywood usa 20, pasadena":            "cinemark hollywood pasadena 20",
    "cinemark 19 + xd, katy":                "cinemark katy 19 + xd",
    "cinemark 12 + xd, pearland":            "cinemark pearland 12 + xd",
    "cinemark 12 + xd, cypress":             "cinemark cypress 12 + xd",
    "cut! by cinemark cypress, cypress":     "Cinemark Cut 8!",
    "cut! by cinemark cypress":              "Cinemark Cut 8!",
    "cinemark 12, rosenberg":                "cinemark rosenberg 12",
    "cinemark 12, victoria":                 "cinemark victoria 12",
    "century 16 + imax, corpus christi":     "cinemark century corpus christi 16 + xd and imax",
    "college station + xd, college station": "cinemark college station 18 + xd",
    "stone hill town center, pflugerville":  "Cinemark Stone Hill Town Ctr Pflugerville 9 *TEMP 5*",
    "stone hill town center":               "Cinemark Stone Hill Town Ctr Pflugerville 9 *TEMP 5*",
    "cinemark 14, round rock":               "cinemark round rock 14",
    "cinemark san antonio 16, san antonio":  "cinemark movies san antonio 16",
    "cinemark hill country galleria 14, bee cave": "Cinemark Hill Country Bee Cave 14",
    "cinemark mccreless mall 10, san antonio":     "Cinemark Mccreless San Antonio 10",
    "southpark meadows 14, austin":          "cinemark southpark mall austin 14",
    "southpark meadows 14":                  "cinemark southpark mall austin 14",
    "movies 8, del rio":                     "cinemark movies del rio 8",
    "cinemark 7, eagle pass":                "cinemark eagle pass 7",
    # ── David Gundrum (Cinemark East/SE — ComScore "Theater #" format) ───────
    "tinseltown usa, rochester":             "Cinemark Tinseltown Cinema Rochester 16",
    "tinseltown usa, erie":                  "Cinemark Tinseltown Erie 17",
    "tinseltown 14, oak ridge":              "Cinemark Tinseltown Oak Ridge 14",
    "tinseltown, salisbury":                 "Cinemark Tinseltown Salisbury 14",
    "cinemark 16, somerdale":                "Cinemark Movies Somerdale 16 + XD",
    "cinemark 7, asheboro":                  "Cinemark Asheboro 7",
    "movies 10, wilmington":                 "Cinemark Movies Wilmington 10",
    "cinemark movies 10, ashland":           "Cinemark Town Cinema Ashland 10",
    "cinemark mccandless crossing, pittsburgh": "Cinemark North Hills 12 + XD",
    "cinemark center township, monaca":      "Cinemark Monaca 12",
    "cinemark 10 bridgeport, bridgeport":    "Cinemark Meadowbrook Mall 10",
    "the carolina cinemark asheville, asheville": "Cinemark Carolina Asheville 14",
    "cinemark city center, newport news":    "Cinemark City Center 12 + XD",
    # ── Clark Film Buying (bring-back booking) — 3 buyers: Codi Kruse, Ken Kruse, Shayla Schuhriemen ──
    # Booker: Roy Wise.  Theater column uses short/local names; Mica uses full circuit names.
    # "theater" → STOP, so single-word bookings need explicit alias (ratio ≥ 0.8 unachievable).
    "centennial theater":       "Centennial Sheridan 6",
    "fox 5 theater":            "Fox Sterling 5",
    # Picture Show circuit: booking abbreviates as "Picture Show N - XX"; all 10 venues score
    # equally on ["picture","show"] alone, so city abbreviation key disambiguates.
    "picture show 12 - bn":     "Picture Show At Berlin",
    "picture show 6 - sa":      "Picture Show Main Street",
    "picture show 6 - bl":      "Picture Show Bloomingdale Court",
    "picture show 8 - cs":      "Picture Show Citadel Crossing",
    "picture show 10 - ew":     "Picture Show At East Windsor",
    "picture show 11 - fr":     "Picture Show At Southcoast Marketplace",
    "picture show 7 - gj":      "Picture Show at Grand Junction",
    "picture show 5 - ma":      "Picture Show Merchants Exchange",
    "picture show 8 - me":      "Picture Show Superstition Springs",
    "picture show 10 - pr":     "Picture Show Frontier Village",
    # Wyo Movies circuit — "studio city" alone hits wrong venue; capitol needs alias
    "studio city 10":           "Studio City East",
    "capitol stadium 12":       "Studio City Capitol Cinema 16 + ARQ",
    # Other single-word or ambiguous booking names
    "cover 4 theater":          "Cover Ft Morgan 4",
    "grand theater":            "Grand Theatre Lander 1",
    "acme theater":             "Acme Theatre Riverton 1",
    # Round 2 (2026-05-13): venues investigated from full 28-venue Clark booking
    # All fail single-word ratio < 0.8 OR are ambiguous within Studio City cluster.
    "montana theatre":          "Montana Theatre Miles City 3",       # "montana" single → 3 Montana venues in ML
    "movies 3":                 "Movies Rawlins 3",                   # "movies" single → many Movies venues
    "ritz theater":             "Ritz Theatre Thomaston 1",           # "ritz" single → 3 Ritz venues
    "studio city foothills":    "Studio City Foothills Gillette 6",   # disambiguate Studio City cluster
    "studio city uw plaza":     "Studio City UW",                     # Mica name has no "Plaza"; "uw" filtered (<3 chars)

    # ── Additional entries (mica_update holdover tab only) — merged 2026-05-13 ──
    'boise stm 22 & imax':  'Regal Edwards Boise 21 ScreenX, 4DX & IMAX',
    'cinemark 12, zanesville':  'cinemark colony square mall',
    'cinemark 14, mansfield':  'cinemark mansfield 14',
    'cinemark 14, strongsville':  'cinemark strongsville 14',
    'fox stm 16 & imax':  'Regal Fox Ashburn 16',
    'hadley theatre stm 16':  'Regal Hadley Cinemas South Plainfield 16',
    'kingstowne stm 16 & rpx':  'Regal Kingstowne Cinema 16',
    'laurel towne centre 12':  'Regal Laurel Town Center 12',
    'movies 16, gahanna':  'cinemark stoneridge plaza movies 16',
    'norton ks':  'norton theatre',
    'norton, ks':  'norton theatre',
    'reg king of prussia 4dx & imax':  'Regal King Of Prussia 16',
    'tinseltown usa + xd, north canton':  'cinemark tinseltown n canton 24+ xd',
    'valley mall stm 16':  'Regal Valley Mall Hagerstown 16',
    'w. des moines jordan creek + xd':  'cinemark century 20 jordan creek and xd',
    'washington township 14':  'Regal Washington Township Sewell 14',

    # ── Jeff Kaufman / Malco Theatres (added 2026-05-15) ──────────────────────
    # Holdover tab; Contact Person = "Jeff Kaufman"
    'cinema 12, olive branch':    'Malco Olive Branch Cinema 12',
    'cinema 12':                  'Malco Olive Branch Cinema 12',   # city-qualified via parser
    'stage, memphis':             'Malco Stage Cinema Bartlett',
    'stage':                      'Malco Stage Cinema Bartlett',
    'cinema 16, ft smith':        'Malco Fort Smith 16',
    'cinema 16, fort smith':      'Malco Fort Smith 16',
    'movies 9, winchester':       'Malco Cinema Winchester 9',
    'movies 9':                   'Malco Cinema Winchester 9',
    'tup commons, tupelo':        'Malco Tupelo Commons 10',
    'tup commons':                'Malco Tupelo Commons 10',
    'malco cinema 8, columbus':   'Malco Columbus 8',
    'malco cinema 8':             'Malco Columbus 8',
    'roxy, dickson':              'Roxy Dickson 8',
    'roxy':                       'Roxy Dickson 8',
    'epic, muskogee':             'Apex Muskogee 6',
    'epic':                       'Apex Muskogee 6',
    'ox commons, oxford':         'Malco Oxford Commons 8',
    'ox commons':                 'Malco Oxford Commons 8',
    # "Pass Naturally" venues that failed in first run — explicit aliases guarantee match
    # (root cause: Mica may virtual-scroll; row off-screen = not in DOM for _FIND_ONE_JS)
    'southaven, memphis':         'Malco Desoto Southaven 16',
    'southaven':                  'Malco Desoto Southaven 16',
    'collierville, memphis':      'Malco Towne Collierville 16',
    'collierville':               'Malco Towne Collierville 16',
    'razorback 16, fayetteville': 'Malco Razorback Cinema Grill & IMAX',
    'razorback 16':               'Malco Razorback Cinema Grill & IMAX',
    'springdale, springdale':     'Malco Springdale Cinema Grill',
    'springdale':                 'Malco Springdale Cinema Grill',
    'jonesboro towne, jonesboro': 'Malco Jonesboro Towne Cinema',
    'jonesboro towne':            'Malco Jonesboro Towne Cinema',
}
